Algoritmo "media"



Var
    nota1,nota2,nota3,media1,media2,media3,mediafinal:Real

Inicio
       escreval("informe a primeira nota")
       leia(nota1)
       escreval("informe a segunda nota")
       leia(nota2)
       escreval("informe a terceira nota")
       leia(nota3)
       media1 <- nota1 * 2/10
       media2 <- nota2 * 3/10
       media3 <- nota3 * 5/10

     mediafinal <- media1+media2+media3
     escreval("sua media final é ",mediafinal)

Fimalgoritmo