Algoritmo "velocidade"


Var
   velocidadeKM, velocidadeMS, horas: real
Inicio
      escreval("Digite  a velocidade do seu veículo:")
      leia(velocidadeKM)
      velocidadeMS <- velocidadeKm / 3.6
      escreval("A velocidade em m/s é: ", velocidadeMS)
      horas <- 432.2 / velocidadeKM
      escreval("O motorista demorará ", horas, " horas para ir de São Paulo até o  Rio de Janeiro")
Fimalgoritmo