Algoritmo " Exercicio 1 "


Var
    vet1: vetor [0..9]  de  inteiro
    vet2: vetor [0..9]  de  inteiro
    contador:inteiro
Inicio
      para contador de  0 ate 9 faca
           escreval("Digite um numero: ")
           leia(vet1[contador])
      fimpara

      para contador de 0 ate 9 faca
           vet2[contador] <- vet1[contador]
           escreval(vet2[contador])
      fimpara
Fimalgoritmo